---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/bookings":
    get:
      summary: list bookings
      responses:
        '200':
          description: successful
    post:
      summary: create booking
      responses:
        '200':
          description: successful
  "/api/v1/bookings/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show booking
      responses:
        '200':
          description: successful
    patch:
      summary: update booking
      responses:
        '200':
          description: successful
    put:
      summary: update booking
      responses:
        '200':
          description: successful
    delete:
      summary: delete booking
      responses:
        '200':
          description: successful
  "/api/v1/resorts":
    get:
      summary: list resorts
      responses:
        '200':
          description: successful
    post:
      summary: create resort
      responses:
        '200':
          description: successful
  "/api/v1/resorts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show resort
      responses:
        '200':
          description: successful
    patch:
      summary: update resort
      responses:
        '200':
          description: successful
    put:
      summary: update resort
      responses:
        '200':
          description: successful
    delete:
      summary: delete resort
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
